default: &default
  adapter: sqlite3
  timeout: 5000
  pool: 5
  database: db/production.sqlite3

development:
  <<: *default

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
