default: &default
  adapter: mysql2
  timeout: 5000
  pool: 5
  username: root
  password: 7R2h2djZ
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: elefanto

test:
  <<: *default
  database: elefanto_test

production:
  <<: *default
  database: elefanto_ror
  username: elefanto_ror
  password: <%= ENV['ELEFANTO_MYSQL_PASS'] %>
  host: localhost
